name: E2E Test

on: push

jobs:
  cypress-chrome:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.13.2-chrome97-ff96
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          install-command: npm run test:e2e:ci:cypress:install
          start: npm start
          wait-on: 'http://localhost:3000'
          browser: chrome
  cypress-firefox:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.13.2-chrome97-ff96
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          install-command: npm run test:e2e:ci:cypress:install
          start: npm start
          wait-on: 'http://localhost:3000'
          browser: firefox
