name: Quality

on:
  push:
    tags-ignore:
      - '**'
    branches-ignore:
      - 'production'

jobs:
  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm run check:ci:types
  check-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm ci --ignore-scripts
      - run: npm run check:eslint
  check-stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm ci --ignore-scripts
      - run: npm run check:stylelint
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm run check:ci:prettier
  check-commit-msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: commitlint_version=$(grep '"@commitlint/cli"' package.json | tail -n 1 | sed -r 's/.*:.*"(.*)",$/\1/')
      - run: git log -1 --pretty=format:"%s" | npx commitlint@$commitlint_version
