name: Quality

on: push

jobs:
  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm ci --ignore-scripts
      - run: npm run check:types
  check-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm ci --ignore-scripts
      - run: npm run check:eslint
  check-stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm ci --ignore-scripts
      - run: npm run check:stylelint
  check-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm ci --ignore-scripts
      - run: npm run check:prettier
  check-commit-msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm ci --ignore-scripts
      - run: git log -1 --pretty=format:"%s" | npx --no-install commitlint
