name: Unit Test

on:
  push:
    tags-ignore:
      - '**'
    branches-ignore:
      - 'production'

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci --ignore-scripts
      - run: npm run test:unit
